# Generated by Django 5.2.8 on 2025-11-12 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidii_builders', '0002_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='property_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bidii_builders.property'),
        ),
    ]
